services:
  - type: web
    name: tailr-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: SALT_ROUNDS
        value: 10
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: ap-south-1
      - key: AWS_BUCKET_NAME
        value: job-app-os-resumes
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: FRONTEND_URL
        value: https://job-app-os.vercel.app
      - key: EXTENSION_ORIGIN
        value: chrome-extension://ohjfcikcenhffkpmppnpcjjegakaifne
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: APP_URL
        sync: false
